### PR TITLE
gracefully handle empty forms

### LINKED ISSUE #131: Uninformative error when initialising a form with no active pages
Related to https://github.com/medic/cht-core/issues/5484 and https://github.com/enketo/enketo-core/issues/662

When rendering an empty form, you get the following error in the console:

```
Form.js:239 TypeError: Cannot read property 'scrollIntoView' of undefined
    at Object.focusOnFirstQuestion (VM30 page.js:277)
    at Object.flipTo (VM30 page.js:235)
    at Object.flipToFirst (VM30 page.js:247)
    at Object.init (VM30 page.js:44)
    at Form.init (Form.js:214)
    at FormWireup.render (wireup.js:37)
    at window.loadXform (index.js:12)
    at doLoad (index.js:27)
    at HTMLAnchorElement.eval (index.js:29)
    at HTMLAnchorElement.dispatch (jquery.js:5206)
```

Harness captures this as two errors:
```
[ ConsoleMessage {
    _type: 'error',
    _text: 'JSHandle@error',
    _args: [ [JSHandle] ],
    _stackTraceLocations: [ [Object], [Object], [Object], [Object] ] },
  ConsoleMessage {
    _type: 'debug',
    _text: 'loadErrors JSHandle@array',
    _args: [ [JSHandle], [JSHandle] ],
    _stackTraceLocations: [ [Object], [Object], [Object], [Object] ] } ]
```

Which then causes the assertion in afterEach to fail since we test to verify that harness.consoleErrors is empty.
This was fixed in cht-core by [patching](https://github.com/medic/cht-core/pull/5941/files) enketo-core

Other issues uncovered while investigating this is that [FormWireup.render](https://github.com/medic/cht-conf-test-harness/blob/6dbef598c35c53cf0bd0757f068539288c1943ab/src/form-host/wireup.js#L40) returns -1 when there enketo encounters errors loading the form but we assume we always pass [FormFiller](https://github.com/medic/cht-conf-test-harness/blob/6dbef598c35c53cf0bd0757f068539288c1943ab/src/form-host/index.js#L13) a valid form. FormFiller [does not validate](https://github.com/medic/cht-conf-test-harness/blob/6dbef598c35c53cf0bd0757f068539288c1943ab/src/form-host/form-filler.js#L8) if the form object passed to it is valid.

### PR DESCRIPTION
**Pull request by derickl**
Resolves #131

I came across this issue when writing a simple test for [this](https://github.com/medic/config-moh-kenya-app/pull/50). A follow up form whose groups are shown depending on what value is passed in via inputs (aka content). Without any value, no groups are activated and you end up with an empty form. 

Concerns: I'm curious if the change made to FormWireup.render is the right one

### CODE REVIEW

File: build.sh [hunk 1]
```diff
@@ -14,6 +14,7 @@ npm ci
 rm -Rf dist build
 rm -Rf node_modules/enketo-core/node_modules/
 patch -f node_modules/enketo-core/src/js/Form.js < node_modules/cht-core-3-11/webapp/patches/enketo-inputs-always-relevant.patch
+patch -f node_modules/enketo-core/src/js/page.js < patches/enketo-handle-no-active-pages.patch
```
Comment (kennsippell) [inline build.sh:17]: does CHT do this?

**Review by kennsippell — CHANGES_REQUESTED** [review]

File: build.sh (hunk 1 above)
Comment (derickl) [reply build.sh:17]: Core has been doing this since [Sep 2019](https://github.com/medic/cht-core/pull/5941/files#diff-8e7e5f941c67b0cf481a9d650295119d4922b96117e7adc069ba30a81a78c65fR597)

Same patch is in [master](https://github.com/medic/cht-core/blob/master/Gruntfile.js#L565)

The only difference is that I remove the console.warning since harness tracks those are errors

File: src/form-host/wireup.js [hunk 2]
```diff
@@ -37,7 +38,6 @@ class FormWireup {
     const loadErrors = form.init();
     if (loadErrors && loadErrors.length) {
       console.log('Load Errors', JSON.stringify(loadErrors));
```
Comment (kennsippell) [inline src/form-host/wireup.js:40]: can you explain why this is required?  it seems like this is maybe a good "fail-fast" return.

Comment (kennsippell) [reply src/form-host/wireup.js:40]: an exception sounds like a good idea. i think that's maybe okay that cht-core doesn't

**Review by kennsippell — APPROVED** [review]
